### ISSUE TITLE
camera

### ISSUE THREAD

**Issue by nesquik011** [edexheim/como#3]
kindly what type of camera is it ? normal mono camera ? or depth camera ?

**Comment by edexheim** [comment]
Hello,

We only use monocular (RGB only) as input.  All dataloaders only return a timestamp and RGB image.  For a live camera dataloader, please see our RealSense example https://github.com/edexheim/como/blob/da616363454591085c3f02715d7d9df04388a19f/como/data/RealsenseDataset.py#L109  Note that we do not use the depth stream at all.

Best,
Eric

**Comment by nesquik011** [comment]
@edexheim how did you manage to get good depth ? i am using stereo camera with slam , and i cant reach 50 % of your depth results i am using SGBM so is that deep learning thing or what is that ?

**Comment by edexheim** [comment]
Hello,

Yes, our system uses a combination of a learned prior combined with multi-view optimization.  Please see our papers linked for more details on the specifics.

Best,
Eric
