### ISSUE TITLE
Obtaining the depth image and camera poses for RGB frames

### ISSUE THREAD

**Issue by ZCMax** [edexheim/como#4]
Imagine that I have a sequence of RGB images, can I use COMO to obtain their corresponding depth images and camera poses?

**Comment by edexheim** [comment]
Hello,

Yes, COMO handles an ordered sequence of RGB images such as from video.  You could implement a dataloader for your data similar to those found in https://github.com/edexheim/como/blob/main/como/data/odom_datasets.py. Note that we do require calibration information.
