### ISSUE TITLE
How does it perform on the KITTI dataset?

### ISSUE THREAD

**Issue by meyiao** [edexheim/como#6]
Thanks for your excellent work, I wonder whether it can perform well on the outdoor scenes.

**Comment by edexheim** [comment]
Hello,

I have not thoroughly tested on the KITTI dataset, as the original prior was trained purely on ScanNet data.  I have tested on smaller outdoor scenes that have some urban elements and it can track reasonably, but KITTI is likely more challenging.  Let me know if you have any more questions.

Eric

**Comment by meyiao** [comment]
Hi Eric,

Thanks for your kind replay.

Have a good day!

Meyiao
